# Generated by Django 4.1 on 2023-08-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, max_length=500, null=True)),
                ("message", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
